### ISSUE TITLE
【確認待ち】 お試し申請の対応を自動化したい

### ISSUE THREAD

**Issue by shimotmk** [vektor-inc/vk-trial-auto-supporter#1]
■名前を決める
https://github.com/vektor-inc/vk-trial-auto-supporter

■プラグインで実装

■毎日自動処理
* データベースのリセット
* テーマ・プラグインのアップデート
* パスワードのリセット

■申請が送信された時
* 現在のゲスト用ユーザーのIDとパスワードを自動返信
* アンケートのフォームURLを記載しておく

■ 注意
* リセット前１時間前くらいからは申請を停止する
* 毎日リセットされる時間を見えるように記載しておく

**Comment by shimotmk** [comment]
@kurudrive 
こちらのプラグインの仕様についてお伺いしたいのですが、よろしいでしょうか。
お訪ねしたいことは”申請フォームのサイトと試用サイトは分けるか”です

現状のお試し利用申請フローはこのような形です
1.VWSのお試し申請ページから申請が送られる
https://vws.vektor-inc.co.jp/contact/theme_trial_order
2.そのメールアドレスに対して試用版サイトのユーザー名とパスワードを送る
http://vs4.nagoya/demo-katawara/

そして私のローカルで申請フォームと試用サイトが同じサイトでユーザーを追加、自動返信メールにパスワードを発行することはできました！

もし分けるのあれば、私の力不足で申し訳ないのですが、実装方法が思いつかないのですがどんなアプローチで行えばいいかご教授願いたいです🙇‍♂️

**Comment by kurudrive** [comment]
@shimotmk おーっつかれっすー！

うぉーい！ Great Job！

Oh!! Sorry....
I see.
確かに申請サイトが別なのを I was perfectly forgotten!!

**Comment by shimotmk** [comment]
申請サイトと試用サイトが別でも大丈夫
その際に試用ユーザーはお問合せフォームの編集権限に制限をつける

(5/24終礼前のお話で)

**Comment by shimotmk** [comment]
@kurudrive 
お疲れさまです！
お試し申請の対応を自動化プラグインおおよそ出来たと思うのでお時間ある時に見ていただけますでしょうか？
https://github.com/vektor-inc/vk-trial-auto-supporter

確認方法
1. 必要なプラグインを有効化する
2. updraftplusでバックアップを作りvk-trial-auto-supporter.phpの62行目のnonceを変更
https://github.com/vektor-inc/vk-trial-auto-supporter/blob/feature/vk-trial-auto-supporter/vk-trial-auto-supporter.php#L62
nonceはlog.〇〇.txtの〇〇の箇所です
3. お問合せフォームの自動返信メールを設定する

以下のようにすれば生成されたパスワードが代入されます
```
お名前
[your-name]

会社名
[your-conpany]

メールアドレス
[your-email]

ユーザー名
vektor-guest

パスワード
generate_password
```

4. フォームからメールを送り返信されたパスワードでログイン出来るか確認
5. 試用ユーザーのようにサイトを編集などする
6. 指定時間になったらパスワードが変わりログアウトされサイトに訪れると復元されていることを確認

別件
すみません
私の設定ミスなのですがGitのデフォルト・ブランチ名がmasterブランチでは無くなってしましました

私の方でgithubのデフォルトブランチを変えることが出来なかったのでmasterなどに変更お願いできますでしょうか
[GitHubでデフォルト・ブランチを変更する](https://parashuto.com/rriver/tools/change-git-default-branch-name#change-github-default-branch
)
お願いいたします🙇‍♂️

**Comment by shimotmk** [comment]
残タスク

- [x]  vktas_optionsのオプション名にする
- [x] optionを配列で持たせる
- [x] プラグインを削除したらオプション値を削除する

**Comment by shimotmk** [comment]
@kurudrive 
再びすみません
以下３点を調整しました
- vktas_optionsのオプション名にする
- optionを配列で持たせる
- プラグインを削除したらオプション値を削除する

https://github.com/vektor-inc/vk-trial-auto-supporter/commit/f50f49e47b8482f56fd59f3c4455920620783c51
お時間ある時にご確認よろしくお願いします

**Comment by kurudrive** [comment]
@shimotmk 
これ確か Updraft の有料版の何か設定しないとコマンド走らないよね（・ｗ・？

**Comment by shimotmk** [comment]
@kurudrive 
お伝え出来てなく、すみません🙇‍♂️

Updraft の有料版の設定が必要です
https://updraftplus.com/support/installing-updraftplus-premium-your-add-on/

上記の記事から有料プラグインをダウンロードして無料プラグインと入れ替えて有料プラグインでUpdraftで作ったアカウントでログインすればUpdraftのコマンドが使えます

有料プラグインの有効化やっておきます！

**Comment by kurudrive** [comment]
@shimotmk よろしくお願いいたします。

あと、

* ブランチは main がマスターブランチに変更しましたん。
* 昨晩少し書き換えたので、好みの問題レベルに近いですが、変更コミット軽く見ておいてください。

**Comment by shimotmk** [comment]
@kurudrive 
ありがとうございます！！！
とても勉強になります🙇‍♂️

updraftplusの有料プラグインの連携完了しました

非公開: お試し申請フォーム
https://vs4.nagoya/demo-katawara/vk_trial/theme_trial_order/

こちらで問題なくコマンドが動くと思います

**Comment by kurudrive** [comment]
@shimotmk ありがとうございます！
これさっき 300sec で確認した割にはもっとたくさんメール通知が来たように思うんだけど、指定時間内でも連続実行されたりしない？

**Comment by shimotmk** [comment]
@kurudrive 
すみません
一旦プラグイン停止しました

もしかすると、スケジュール名(関数名)を変えた関係で過去に設定したスケジュールも動いてしまっているのかもです
調整します

**Comment by kurudrive** [comment]
@shimotmk 

> スケジュール名(関数名)を変えた関係で過去に設定したスケジュールも動いてしまっているのかもです

そうだったらすまぬ...。
スケジュール実行うまくいかなかったら、
実行した時に最終実行時間保存して、そこからインターバル時間内だったら事項しないとかの処理でもいいかも。
（あくまで参考程度の意見デス）
