### ISSUE TITLE
スケジュールの挙動が怪しい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-trial-auto-supporter#5]
やはり連続処理されてしまう。

https://vs4.nagoya/demo-katawara/
で直接動作調整よろしくお願いいたします (￣人￣) 。

**Comment by shimotmk** [comment]
@kurudrive 
何度も、すみません🙏

復元が実行された時間から１日以上経過した時に次の復元が起きるように[以前頂いた案](https://github.com/vektor-inc/vk-trial-auto-supporter/issues/1#issuecomment-853559776)で調整しました
https://github.com/vektor-inc/vk-trial-auto-supporter/pull/7/files

もしイベントを実行したい場合は52行目辺りの86400を任意の秒数に変更して管理画面の「ツール > Cron イベント」からvktas_auto_cronの「今すぐ実行」を押せば強制的にイベントを実行出来ます

もしあれでしたら直接動作確認をしていただけたらと思いますが、いかがでしましょう？

**Comment by shimotmk** [comment]
お試し申請プロジェクト残り作業

- [x] お試し申請のフォームページを公開する
https://vs4.nagoya/demo-katawara/vk_trial/theme_trial_order/
- [x] お試し申請のページから申請フォームページのリンクを貼る
https://vws.vektor-inc.co.jp/contact/theme_trial_order
←こちらのページとフォームは非公開
https://www.vektor-inc.co.jp/service/wordpress-theme/katawara/
←こちらのページのリンクを張替える


です
本日6/7のお試しユーザーさんのお問い合わせがあるので明日以降に上記残り作業を行います
